name: windows

on: [push]

jobs:
  test:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        compiler: [dmd, ldc]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~\AppData\Local\dub
        key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.json') }}
        restore-keys: |
          ${{ runner.os }}-dub-

    - name: download-tf
      run: |
        Invoke-WebRequest "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.15.0.zip" -OutFile tf.zip
        7z x tf.zip
        cp lib/* .

    - name: test-dmd
      if: ${{ matrix.compiler == 'dmd' }}
      run: |
        Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/2.091.1/dmd.2.091.1.windows.7z" -OutFile dmd.7z
        7z x dmd.7z
        dmd2/windows/bin64/dub test --parallel -b=unittest-cov

    - name: test-ldc
      if: ${{ matrix.compiler == 'ldc' }}
      run: |
        Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v1.21.0/ldc2-1.21.0-windows-x64.7z" -OutFile ldc.7z
        7z x ldc.7z
        ldc2-1.21.0-windows-x64/bin/dub test --parallel -b=unittest-cov
